apiVersion: v2
name: dakr-operator
description: A Helm chart for DevZero DAKR - Kubernetes workload optimization and live migration
type: application
version: 0.1.16
appVersion: "0.1.16"
home: https://github.com/devzero-inc/dakr
sources:
  - https://github.com/devzero-inc/dakr
icon: https://devzero-dashboard.b-cdn.net/logo.png
maintainers:
  - name: DevZero Team
    email: support@devzero.io
keywords:
  - optimization
  - kubernetes
  - workload-migration
  - resource-management
  - scheduling
  - devzero
