apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.operator.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dakr.labels" . | nindent 4 }}
  {{- with .Values.operator.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "dakr.fullname" . }}-operator-role
  labels:
    {{- include "dakr.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["get", "list", "watch", "update"]
- apiGroups: ["apps"]
  resources: ["*"]
  verbs: ["get", "list", "watch", "update"]
- apiGroups: ["batch"]
  resources: ["*"]
  verbs: ["get", "list", "watch", "update"]
- apiGroups: ["dakr.devzero.io"]
  resources: ["workloadrecommendations", "nodegrouprecommendations"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["dakr.devzero.io"]
  resources: ["workloadrecommendations/status", "nodegrouprecommendations/status"]
  verbs: ["get", "update", "patch"]
- apiGroups: ["dakr.devzero.io"]
  resources: ["workloadrecommendations/finalizers", "nodegrouprecommendations/finalizers"]
  verbs: ["update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "dakr.fullname" . }}-operator-crb
  labels:
    {{- include "dakr.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "dakr.fullname" . }}-operator-role
subjects:
- kind: ServiceAccount
  name: {{ .Values.operator.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "dakr.fullname" . }}-operator-leader-election-role
  labels:
    {{- include "dakr.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "dakr.fullname" . }}-operator-leader-election-rb
  labels:
    {{- include "dakr.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "dakr.fullname" . }}-operator-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ .Values.operator.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
