apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.operator.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dakr.labels" . | nindent 4 }}
  {{- with .Values.operator.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "dakr.fullname" . }}-operator-role
  labels:
    {{- include "dakr.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["get", "list", "watch", "update", "patch", "create", "delete"]
- apiGroups: ["apps"]
  resources: ["*"]
  verbs: ["get", "list", "watch", "update", "patch", "create", "delete"]
- apiGroups: ["batch"]
  resources: ["*"]
  verbs: ["get", "list", "watch", "update", "patch", "create", "delete"]
- apiGroups: ["events.k8s.io"]
  resources: ["events"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups: ["dakr.devzero.io"]
  resources: ["workloadrecommendations", "nodegrouprecommendations"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["dakr.devzero.io"]
  resources: ["workloadrecommendations/status", "nodegrouprecommendations/status"]
  verbs: ["get", "update", "patch"]
- apiGroups: ["dakr.devzero.io"]
  resources: ["workloadrecommendations/finalizers", "nodegrouprecommendations/finalizers"]
  verbs: ["update"]
- apiGroups: ["dakr.devzero.io"]
  resources: ["checkpointrestores"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["dakr.devzero.io"]
  resources: ["checkpointrestores/status"]
  verbs: ["get"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["clusterroles"]
  verbs: ["get", "list", "watch", "update", "patch", "escalate"]
- apiGroups:
  - "karpenter.sh"
  - "karpenter.k8s.aws"
  - "karpenter.azure.com"
  - "karpenter.gke.io"
  resources: ["*"]
  verbs: ["*"]
{{- if .Capabilities.APIVersions.Has "keda.sh/v1alpha1/ScaledObject" }}
- apiGroups: ["keda.sh"]
  resources: ["scaledobjects"]
  verbs: ["get", "list", "update", "patch"]
{{- end }}
{{- if .Capabilities.APIVersions.Has "argoproj.io/v1alpha1/Application" }}
- apiGroups: ["argoproj.io"]
  resources: ["applications"]
  verbs: ["get", "list", "watch", "update", "patch"]
{{- end }}
{{- if .Capabilities.APIVersions.Has "argoproj.io/v1alpha1/Rollout" }}
- apiGroups: ["argoproj.io"]
  resources: ["rollouts"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: ["argoproj.io"]
  resources: ["rollouts/status"]
  verbs: ["get", "update", "patch"]
{{- end }}
{{- if .Capabilities.APIVersions.Has "kubeflow.org/v1/Notebook" }}
- apiGroups: ["kubeflow.org"]
  resources: ["notebooks"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: ["kubeflow.org"]
  resources: ["notebooks/status"]
  verbs: ["get", "update", "patch"]
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "dakr.fullname" . }}-operator-crb
  labels:
    {{- include "dakr.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "dakr.fullname" . }}-operator-role
subjects:
- kind: ServiceAccount
  name: {{ .Values.operator.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "dakr.fullname" . }}-operator-leader-election-role
  labels:
    {{- include "dakr.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "dakr.fullname" . }}-operator-leader-election-rb
  labels:
    {{- include "dakr.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "dakr.fullname" . }}-operator-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ .Values.operator.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
